# Generated by Django 3.2.20 on 2023-10-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('specialty', models.CharField(max_length=100)),
                ('welcome_text', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=50)),
                ('relocation_status', models.BooleanField()),
                ('professional_experience', models.TextField()),
                ('education', models.TextField()),
                ('about_me', models.TextField()),
                ('photo', models.ImageField(upload_to='applicants/')),
            ],
        ),
    ]
