# Generated by Django 3.2.20 on 2023-10-25 15:52

import app_hr.validate
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(error_messages={'unique': 'Такая компания существует'}, max_length=120, unique=True, validators=[app_hr.validate.validate_username])),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ('name_company',),
            },
        ),
        migrations.CreateModel(
            name='Hardskils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'такой хард скил уже есть в бд'}, max_length=100, unique=True, verbose_name='Название Тега')),
                ('slug', models.SlugField(error_messages={'unique': 'такой slug уже есть'}, max_length=100, unique=True, verbose_name='Уникальный Тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateIns', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('description', models.TextField(help_text='напишите о вакансии', verbose_name='описание вакансии')),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('education', models.CharField(max_length=100, verbose_name='Образование')),
                ('employmentType', models.CharField(max_length=120, verbose_name='Вид занятости')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=120, verbose_name='Город')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='app_hr.company', verbose_name='Автор вакансии')),
                ('specialty', models.ManyToManyField(to='app_hr.Hardskils', verbose_name='Харды')),
            ],
        ),
    ]
