# Generated by Django 3.2.20 on 2023-10-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hr', '0002_alter_vacancy_author_vacancy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hardskils',
            options={'ordering': ('name',), 'verbose_name': 'Хард скил', 'verbose_name_plural': 'Хард скилы'},
        ),
        migrations.AlterModelOptions(
            name='jobexpiriense',
            options={'ordering': ('jobexpiriense',), 'verbose_name': 'занятость', 'verbose_name_plural': 'занятости'},
        ),
        migrations.AlterModelOptions(
            name='projectactivities',
            options={'ordering': ('projectActivities',), 'verbose_name': 'проетной активность', 'verbose_name_plural': 'проетной активности'},
        ),
        migrations.AlterModelOptions(
            name='specializationtype',
            options={'ordering': ('specializationType',), 'verbose_name': 'специализация', 'verbose_name_plural': 'специализации'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'ordering': ('specialty',), 'verbose_name': 'специальность', 'verbose_name_plural': 'специальности'},
        ),
        migrations.AlterField(
            model_name='projectactivities',
            name='projectActivities',
            field=models.CharField(error_messages={'unique': 'такая проетной активности есть в бд'}, max_length=130, unique=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='specializationtype',
            name='specializationType',
            field=models.CharField(error_messages={'unique': 'такая специализациия есть в бд'}, max_length=130, unique=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='specialty',
            field=models.CharField(error_messages={'unique': 'такая специальность в бд'}, max_length=130, unique=True, verbose_name='Образование'),
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='employmentType',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employmentType',
            field=models.ManyToManyField(to='app_hr.Employment', verbose_name='Тип занятости'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='max_salary',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='min_salary',
            field=models.IntegerField(),
        ),
    ]
