# Generated by Django 3.2.20 on 2023-10-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hr', '0003_auto_20231028_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='active_vacancy',
            field=models.BooleanField(default=True),
        ),
    ]
